name: test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm ci

      - name: Run build
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      
      - name: Run lint
        run: npm run lint

      # - uses: convictional/trigger-workflow-and-wait@v1.6.1
      #   with:
      #     owner: wuttichai-beamcheckout
      #     repo: ae-test
      #     github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #     workflow_file_name: dispatch.yml
      #     ref: master
      #     client_payload: '{"url":"hello"}'