name: test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Run build
        run: yarn run build

      - name: Cache build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Restore build
        id: restore-build
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Run lint
        run: yarn run lint


  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Restore build
        id: restore-build
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Run test
        run: yarn run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
